export const HERO_ICONS = [
    'AcademicCapIcon', 'AdjustmentsHorizontalIcon', 'AdjustmentsVerticalIcon', 'ArchiveBoxArrowDownIcon',
    'ArchiveBoxIcon', 'ArchiveBoxXMarkIcon', 'ArrowDownCircleIcon', 'ArrowDownIcon', 'ArrowDownLeftIcon',
    'ArrowDownOnSquareIcon', 'ArrowDownOnSquareStackIcon', 'ArrowDownRightIcon', 'ArrowDownTrayIcon',
    'ArrowLeftCircleIcon', 'ArrowLeftEndOnRectangleIcon', 'ArrowLeftIcon', 'ArrowLeftOnRectangleIcon',
    'ArrowLeftStartOnRectangleIcon', 'ArrowLongDownIcon', 'ArrowLongLeftIcon', 'ArrowLongRightIcon',
    'ArrowLongUpIcon', 'ArrowPathIcon', 'ArrowPathRoundedSquareIcon', 'ArrowRightCircleIcon',
    'ArrowRightEndOnRectangleIcon', 'ArrowRightIcon', 'ArrowRightOnRectangleIcon', 'ArrowRightStartOnRectangleIcon',
    'ArrowTopRightOnSquareIcon', 'ArrowTrendingDownIcon', 'ArrowTrendingUpIcon', 'ArrowUpCircleIcon',
    'ArrowUpIcon', 'ArrowUpLeftIcon', 'ArrowUpOnSquareIcon', 'ArrowUpOnSquareStackIcon', 'ArrowUpRightIcon',
    'ArrowUpTrayIcon', 'ArrowUturnDownIcon', 'ArrowUturnLeftIcon', 'ArrowUturnRightIcon', 'ArrowUturnUpIcon',
    'ArrowsPointingInIcon', 'ArrowsPointingOutIcon', 'ArrowsRightLeftIcon', 'ArrowsUpDownIcon', 'AtSymbolIcon',
    'BackspaceIcon', 'BackwardIcon', 'BanknotesIcon', 'Bars2Icon', 'Bars3BottomLeftIcon', 'Bars3BottomRightIcon',
    'Bars3CenterLeftIcon', 'Bars3Icon', 'Bars4Icon', 'BarsArrowDownIcon', 'BarsArrowUpIcon', 'Battery0Icon',
    'Battery100Icon', 'Battery50Icon', 'BeakerIcon', 'BellAlertIcon', 'BellIcon', 'BellSlashIcon', 'BoltIcon',
    'BoltSlashIcon', 'BookOpenIcon', 'BookmarkIcon', 'BookmarkSlashIcon', 'BriefcaseIcon', 'BugAntIcon',
    'BuildingLibraryIcon', 'BuildingOffice2Icon', 'BuildingOfficeIcon', 'BuildingStorefrontIcon', 'CakeIcon',
    'CalculatorIcon', 'CalendarDaysIcon', 'CalendarIcon', 'CameraIcon', 'ChartAreaIcon', 'ChartBarIcon',
    'ChartBarSquareIcon', 'ChartPieIcon', 'ChatBubbleBottomCenterIcon', 'ChatBubbleBottomCenterTextIcon',
    'ChatBubbleLeftEllipsisIcon', 'ChatBubbleLeftIcon', 'ChatBubbleLeftRightIcon', 'ChatBubbleOvalLeftEllipsisIcon',
    'ChatBubbleOvalLeftIcon', 'CheckBadgeIcon', 'CheckCircleIcon', 'CheckIcon', 'ChevronDoubleDownIcon',
    'ChevronDoubleLeftIcon', 'ChevronDoubleRightIcon', 'ChevronDoubleUpIcon', 'ChevronDownIcon', 'ChevronLeftIcon',
    'ChevronRightIcon', 'ChevronUpDownIcon', 'ChevronUpIcon', 'CircleStackIcon', 'ClipboardDocumentCheckIcon',
    'ClipboardDocumentIcon', 'ClipboardDocumentListIcon', 'ClipboardIcon', 'ClockIcon', 'CloudArrowDownIcon',
    'CloudArrowUpIcon', 'CloudIcon', 'CodeBracketIcon', 'CodeBracketSquareIcon', 'Cog6ToothIcon', 'Cog8ToothIcon',
    'CogIcon', 'CommandLineIcon', 'ComputerDesktopIcon', 'CpuChipIcon', 'CreditCardIcon', 'CubeIcon',
    'CubeTransparentIcon', 'CurrencyBangladeshiIcon', 'CurrencyEuroIcon', 'CurrencyPoundIcon', 'CurrencyRupeeIcon',
    'CurrencyYenIcon', 'CursorArrowRaysIcon', 'CursorArrowRippleIcon', 'DevicePhoneMobileIcon', 'DeviceTabletIcon',
    'DocumentArrowDownIcon', 'DocumentArrowUpIcon', 'DocumentChartBarIcon', 'DocumentCheckIcon', 'DocumentDuplicateIcon',
    'DocumentIcon', 'DocumentMagnifyingGlassIcon', 'DocumentMinusIcon', 'DocumentPlusIcon', 'DocumentTextIcon',
    'DocumentXMarkIcon', 'EllipsisHorizontalCircleIcon', 'EllipsisHorizontalIcon', 'EllipsisVerticalIcon',
    'EnvelopeIcon', 'EnvelopeOpenIcon', 'ExclamationCircleIcon', 'ExclamationTriangleIcon', 'EyeIcon',
    'EyeSlashIcon', 'FaceFrownIcon', 'FaceSmileIcon', 'FilmIcon', 'FingerPrintIcon', 'FireIcon', 'FlagIcon',
    'FolderArrowDownIcon', 'FolderIcon', 'FolderMinusIcon', 'FolderPlusIcon', 'FolderOpenIcon', 'ForwardIcon',
    'FunnelIcon', 'GifIcon', 'GiftIcon', 'GlobeAltIcon', 'GlobeAmericasIcon', 'GlobeAsiaAustraliaIcon',
    'GlobeEuropeAfricaIcon', 'HandRaisedIcon', 'HandThumbDownIcon', 'HandThumbUpIcon', 'HashtagIcon',
    'HeartIcon', 'HomeIcon', 'HomeModernIcon', 'IdentificationIcon', 'InboxArrowDownIcon', 'InboxIcon',
    'InboxStackIcon', 'InformationCircleIcon', 'KeyIcon', 'LanguageIcon', 'LifebuoyIcon', 'LightBulbIcon',
    'LinkIcon', 'ListBulletIcon', 'LockClosedIcon', 'LockOpenIcon', 'MagnifyingGlassCircleIcon',
    'MagnifyingGlassIcon', 'MagnifyingGlassMinusIcon', 'MagnifyingGlassPlusIcon', 'MapIcon', 'MapPinIcon',
    'MegaphoneIcon', 'MicrophoneIcon', 'MinusCircleIcon', 'MinusIcon', 'MoonIcon', 'MusicalNoteIcon',
    'NewspaperIcon', 'NoSymbolIcon', 'PaintBrushIcon', 'PaperAirplaneIcon', 'PaperClipIcon', 'PauseCircleIcon',
    'PauseIcon', 'PencilIcon', 'PencilSquareIcon', 'PhoneArrowDownLeftIcon', 'PhoneArrowUpRightIcon', 'PhoneIcon',
    'PhoneXMarkIcon', 'PhotoIcon', 'PlayCircleIcon', 'PlayIcon', 'PlayPauseIcon', 'PlusCircleIcon', 'PlusIcon',
    'PowerIcon', 'PresentationChartBarIcon', 'PresentationChartLineIcon', 'PrinterIcon', 'PuzzlePieceIcon',
    'QrCodeIcon', 'QuestionMarkCircleIcon', 'QueueListIcon', 'RadioIcon', 'ReceiptPercentIcon', 'ReceiptRefundIcon',
    'RectangleGroupIcon', 'RectangleStackIcon', 'RocketLaunchIcon', 'RssIcon', 'ScaleIcon', 'ScissorsIcon',
    'ServerIcon', 'ServerStackIcon', 'ShareIcon', 'ShieldCheckIcon', 'ShieldExclamationIcon', 'ShoppingBagIcon',
    'ShoppingCartIcon', 'SignalIcon', 'SignalSlashIcon', 'SparklesIcon', 'SpeakerWaveIcon', 'SpeakerXMarkIcon',
    'Square2StackIcon', 'Square3Stack3DIcon', 'Squares2x2Icon', 'SquaresPlusIcon', 'StarIcon', 'StopCircleIcon',
    'StopIcon', 'SunIcon', 'SwatchIcon', 'TableCellsIcon', 'TagIcon', 'TicketIcon', 'TrashIcon', 'TrophyIcon',
    'TruckIcon', 'TvIcon', 'UserCircleIcon', 'UserGroupIcon', 'UserIcon', 'UserMinusIcon', 'UserPlusIcon',
    'VariableIcon', 'VideoCameraIcon', 'VideoCameraSlashIcon', 'ViewColumnsIcon', 'ViewfinderCircleIcon',
    'WalletIcon', 'WifiIcon', 'WindowIcon', 'WrenchIcon', 'WrenchScrewdriverIcon', 'XCircleIcon', 'XMarkIcon'
];

