<template>
    <div>
        <div class="flex justify-between items-center mb-6">
            <div>
                <!-- Group Breadcrumbs -->
                <div class="mb-2 flex items-center gap-4">
                    <router-link :to="{ name: 'admin.settings.index' }" class="text-indigo-600 hover:text-indigo-700 font-medium flex items-center text-sm">
                        <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to Hub
                    </router-link>
                </div>
                
                <div class="flex items-center gap-3">
                    <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Webhooks</h1>
                </div>
                <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">Manage webhooks generated by Sandbox Apps or Custom UI</p>
            </div>
            <div class="flex gap-2">
                <button
                    @click="loadWebhooks"
                    class="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 transition-colors"
                >
                    Refresh
                </button>
                <button
                    @click="$router.push({ name: 'admin.webhooks.create' })"
                    class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                >
                    Add Webhook
                </button>
            </div>
        </div>

        <div v-if="loading" class="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow">
            <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
            <p class="mt-2 text-gray-600 dark:text-gray-400">Loading webhooks...</p>
        </div>

        <div v-else class="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-gray-50 dark:bg-gray-700">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Module</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">URL</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Events</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Deliveries</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Status</th>
                        <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                    <tr v-if="webhooks.length === 0">
                        <td colspan="6" class="px-6 py-12 text-center text-sm text-gray-500 dark:text-gray-400">
                            No webhooks configured yet.
                        </td>
                    </tr>
                    <tr v-for="webhook in webhooks" :key="webhook.id" class="hover:bg-gray-50 dark:hover:bg-gray-700">
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm font-medium text-gray-900 dark:text-white">{{ webhook.name }}</div>
                            <div class="text-xs text-gray-500 dark:text-gray-400">{{ webhook.module_slug }}</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm text-gray-900 dark:text-white max-w-[200px] truncate" :title="webhook.url">
                                {{ webhook.url }}
                            </div>
                        </td>
                        <td class="px-6 py-4">
                            <div class="flex flex-wrap gap-1 max-w-[250px]">
                                <span v-for="event in webhook.events" :key="event" class="px-2 py-0.5 rounded text-xs bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200">
                                    {{ event }}
                                </span>
                            </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                            {{ webhook.deliveries_count || 0 }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <button 
                                @click="toggleWebhook(webhook)"
                                :disabled="togglingId === webhook.id"
                                :class="[
                                    'relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500',
                                    webhook.is_active ? 'bg-indigo-600' : 'bg-gray-200 dark:bg-gray-600',
                                    (togglingId === webhook.id) ? 'opacity-50 cursor-not-allowed' : ''
                                ]"
                            >
                                <span class="sr-only">Toggle webhook</span>
                                <span 
                                    aria-hidden="true" 
                                    :class="[
                                        'pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200',
                                        webhook.is_active ? 'translate-x-5' : 'translate-x-0'
                                    ]"
                                />
                            </button>
                            <span class="ml-2 text-sm text-gray-500 dark:text-gray-400 align-middle">
                                {{ webhook.is_active ? 'Active' : 'Muted' }}
                            </span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div class="flex items-center justify-end gap-2">
                                <button @click="pingWebhook(webhook)" class="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300" title="Test Ping">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                                </button>
                                <button @click="$router.push({ name: 'admin.webhooks.edit', params: { id: webhook.id } })" class="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300" title="Edit">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg>
                                </button>
                                <button @click="deleteWebhook(webhook)" class="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300" title="Delete">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import axios from 'axios';
import { useDialog } from '../../composables/useDialog';

const webhooks = ref<any[]>([]);
const loading = ref(false);
const togglingId = ref<number | null>(null);
const dialog = useDialog();

const loadWebhooks = async () => {
    loading.value = true;
    try {
        const response = await axios.get('/api/v1/webhooks');
        webhooks.value = response.data.data;
    } catch (e: any) {
        dialog.error(e.response?.data?.message || 'Failed to load webhooks');
    } finally {
        loading.value = false;
    }
};

const toggleWebhook = async (webhook: any) => {
    if (togglingId.value === webhook.id) return;
    
    togglingId.value = webhook.id;
    try {
        const response = await axios.patch(`/api/v1/webhooks/${webhook.id}/toggle`);
        webhook.is_active = response.data.data.is_active;
        dialog.success(response.data.message);
    } catch (e: any) {
        dialog.error(e.response?.data?.message || 'Failed to toggle webhook state');
    } finally {
        togglingId.value = null;
    }
};

const deleteWebhook = async (webhook: any) => {
    if (!await dialog.confirm('Are you sure you want to delete this webhook? This cannot be undone.')) {
        return;
    }

    try {
        await axios.delete(`/api/v1/webhooks/${webhook.id}`);
        dialog.success('Webhook deleted successfully');
        loadWebhooks();
    } catch (e: any) {
        dialog.error(e.response?.data?.message || 'Failed to delete webhook');
    }
};

const pingWebhook = async (webhook: any) => {
    try {
        dialog.success('Dispatching ping test...');
        const res = await axios.post(`/api/v1/webhooks/${webhook.id}/ping`);
        dialog.success(res.data.message || 'Ping payload dispatched');
    } catch (e: any) {
        dialog.error(e.response?.data?.message || 'Failed to test webhook');
    }
};

onMounted(() => {
    loadWebhooks();
});
</script>
